### PR TITLE
Updating visual studio url

### PR DESCRIPTION
**Pull request by sayedihashimi**
Updating to the correct url for the VS extension

### CODE REVIEW

**Comment by l0rd** [comment]
Thank you @sayedihashimi!

**Comment by l0rd** [comment]
@sayedihashimi how did you find out about domeide.github.io?

**Comment by sayedihashimi** [comment]
I was searching GitHub for VS + Docker content.

**Comment by l0rd** [comment]
Ok. I asked because I haven't update the site in the last year and half and I was curious on how you had the link. Thank again for you patch @sayedihashimi

**Pull request merged**
