### PR TITLE
Add links to emacs docker interfaces

### PR DESCRIPTION
**Pull request by Silex**

### CODE REVIEW

**Comment by l0rd** [comment]
Thanks for the links! By the way dockerfile-mode has already been mentioned in #11 and if you could provide a screenshot and a short descrition (cf. #11 ) it would be apreciated.

**Comment by Silex** [comment]
Screenshot for `docker.el`? a bit too early for that, package is usable but really in early development.

Ping me again in one week, I should have something more stable.

**Comment by Silex** [comment]
Also, merge #11 already and I'll rebase my commits :)

**Comment by l0rd** [comment]
#11 is merged. Ok for the screenshot.

**Pull request closed without merging**
